/*const mySurname = "Onuorah";
const myAge = 25;

const logic = myAge === 25 && mySurname === "Onuorah"

console.log(logic);*/

/* and operator (&&) returns true if both conditions are true, otherwise it returns false. In this case, both conditions are true, so the output will be true.
or operator (||) returns true if either of the conditions is true. If both conditions are false, it returns false.
not operator (!) returns true if the condition is false, and false if the condition is true. */

/*if(myAge>= 18) { console.log ('you are eligible to vote')}*/
 
const day = "Thursday";

switch (day) {
    case 'Monday':
        console.log('I hate Mondays');
        break
    case 'Tuesday' :
        console.log('let me just survive today!');
        break;
    default:
        console.log('Enjoy the rest of the week!') }  

